### PR TITLE
Update target attribute of popover controller

### PR DESCRIPTION
**Pull request by ozovalihasan**
One of target attributes is updated [as suggested](https://stimulus.hotwired.dev/reference/targets).

### CODE REVIEW

**Comment by excid3** [comment]
Thanks!

**Comment by ozovalihasan** [comment]
The same target attribute in another file is updated.

**Comment by ozovalihasan** [comment]
I updated a few more target attributes to make commented codes consistent.

**Comment by excid3** [comment]
Perfect, appreciate it @ozovalihasan 👍

**Pull request merged**
