### PR TITLE
history.replaceState is not compatible with turbo

### PR DESCRIPTION
**Pull request by dbil25**
history.replaceState is not compatible with turbo. it breaks the page caching (when hitting previous/next)

got the turbo code from here: https://github.com/hotwired/turbo/issues/335

### CODE REVIEW

**Comment by excid3** [comment]
Looks like this has some issues as well? 

> * User cannot return to the previous state anymore
> * Preview holds outdated state


https://github.com/hotwired/turbo/issues/335#issuecomment-1311720245

**Comment by dbil25** [comment]
Oops i skipped past those apparently 😕. When i tried, it totally fixed it though. 

The issue is simple to reproduce, just click a link in a turbo app while in a page that contains this tab component, then pressing previous does not work at all.

I'll dig around next to try and find a perfect solution.

**Comment by dbil25** [comment]
I don't understand what pySilver is refering to. It works flawlessly and doesnt break the state. In the discussion he is referring to, he is trying to do a 'pushState' not a 'replaceState', which might be why he said that we "lose the previous state", but in this case its expected. I dont really see a problem with this approach, and when looking at turbo source code, it just does a history.replaceState but with a little additional turbo stuff to keep the cache intact: https://github.com/hotwired/turbo/blob/9fb05e3ed3ebb15fe7b13f52941f25df425e3d15/src/core/drive/history.js#L38

**Comment by excid3** [comment]
I just need to test this in a Turbo app, but this seems good to me.

**Comment by dillonhafer** [comment]
I'm using the tabs.js file from this PR to work around this bug for now.

**Comment by erlinghaugstad** [comment]
Me too, was trying to circumvent this by calling my own custom controller to fix this behaviour, but was unable to make it work. 

Can this be released?

**Pull request merged**
