### PR TITLE
Adds ability to sync tabs instances by group

### PR DESCRIPTION
**Pull request by anthony0030**
We have a page that uses the tabs component for inputs in different languages, one tab per language.
We want to be able to change all the tabs at once.

### CODE REVIEW

**Comment by anthony0030** [comment]
I just realized there are also tests to do. I will try to fill them in tomorrow.

**Comment by anthony0030** [comment]
@excid3 could you please take a look at this before I write the test to see if the implementation is any good and that this is a usefull feature for more peaple.

**Comment by excid3** [comment]
It feels a bit niche, so I'm not sure if we want to maintain that.

How about doing this as a separate controller that inherits and extends the Tab controller?

**Comment by excid3** [comment]
Excellent! I will close this but it'll be a great reference for anyone else trying to do similar things. Thanks for sharing! 👍

**Pull request closed without merging**
