### PR TITLE
update tabs docs to use props that match tabs implementation

### PR DESCRIPTION
**Pull request by cjavdev**

### CODE REVIEW

**Comment by excid3** [comment]
I see you @cjavdev 👀

**Comment by cjavdev** [comment]
haha. I think the docs are wrong, but I went to make a proper fix and write a test etc because I think the fixtures are wrong also, but I couldn't get the tests running in the 5 min I carved out to mess with this :D

**Comment by excid3** [comment]
v4 was updated to use the stimulus classes API. v3 and below use that old style. Which version are you on?

**Comment by cjavdev** [comment]
I guess I had an old version locally! Works in prod. Sorry for the noise :)

-- CJ

**Pull request closed without merging**
