### PR TITLE
Catch the finished promise AbortError and ignores it

### PR DESCRIPTION
**Pull request by jaywhy**
Fixes issue https://github.com/excid3/tailwindcss-stimulus-components/issues/247 by putting duct tape over it.

### CODE REVIEW

**Comment by excid3** [comment]
Think there's any downsides to doing this?

**Comment by jaywhy** [comment]
Yes, I think there could be unforeseen downsides.

Thinking about it more, I wouldn't say I like this patch. It doesn't fix the problem, it just covers it up. If the `AbortError` is caught, animation glitches still occur.  It only fixes the issue with `Promise.all` rejecting **ALL** animations when one promise is rejected. So, one animation won't cause others to stop.

I tested el-transition and Alpine.js yesterday. el-transition has the same problem. Alpine.js doesn't, but the Alpine folks do something completely different in their transition library.

I have some time later this week. I can look into it more.

**Comment by jaywhy** [comment]
Ok. I tried to fix it without rewriting it, but I couldn't get that to work.

Are you okay with me rewriting the transition.js library like this? 

The code fixes the issues with `AbortError`'s. The transition code now works sort of like Alpine.js.  It sets a `_stimulus_transitions` property on the element, and if another transition comes along and sees that, it will cancel the already running transition.

However, the new transition.js breaks some tests. But I think the broken tests are all timing-related or race condition-like things because the code no longer awaits on the animation Promises. I don't think this will affect production code unless someone relies on these weird timing inconsistencies. Famous last words, though.

I'll give a couple of examples of the test problems...

The `dropdown_test.js` needs to run `await nextFrame()` twice, not once, for it to pass. It requires two calls because the `transition.js` calls `requestAnimationFrame` twice and doesn't use `await`.

One of the `alert_test.js` tests breaks because the `closeButton.click()` event in that test now happens before the `setTimeout()` in `AlertController#connect()` gets to run. The `click()` calls `leave()`, and then the `setTimeout()` code runs, calling `enter()`, which cancels the `leave()`.

If you're ok with this change, I'll clean things up, fix the broken tests, and squash my commits.

**Comment by excid3** [comment]
This is looking good @jaywhy! Will give it a test locally later today, but it seems good to me.

**Comment by excid3** [comment]
Looks like it's working great!

Anything else to do or is it ready to merge?

**Comment by jaywhy** [comment]
Yes. I think so.

**Comment by excid3** [comment]
Thanks so much for this @jaywhy 👍

**Pull request merged**
