### PR TITLE
Rewrite dropdown controller to support transitions

### PR DESCRIPTION
**Pull request by julianrubisch**
This PR introduces inactive, entering and leaving classes (plus respective timeouts) for transitions.

As far as I can tell this should leave the public API intact.

The implementation is a bit intricate, maybe we can simplify it a bit. The `setTimeout` here: 

https://github.com/excid3/tailwindcss-stimulus-components/compare/master...julianrubisch:dropdown-transitions?expand=1#diff-6551d9079d8c312990e2a4a181c31ee3R46

was necessary because otherwise the entering transition wouldn't start but immediately show the dropdown - don't ask me :-)

### CODE REVIEW

**Comment by excid3** [comment]
Thanks @julianrubisch! Looks pretty good and I'm sure this added complexity is probably required for transitions.

I am testing this locally and it seems like opening the dropdown toggles the `dropdown-active-class` on the parent element of the dropdown. It's making the entire navbar change background colors, so it doesn't seem right. Bug?

**Comment by julianrubisch** [comment]
Yeah probably 😏 I was almost sure this is gonna need a second pass.

**Comment by julianrubisch** [comment]
So I think I didn't quite understand the API. In your implementation, you're switching the `_activeClassList` on the `active-target`. So even on https://excid3.github.io/tailwindcss-stimulus-components/ I see the color of the navbar changing. 

What am I missing?

**Comment by julianrubisch** [comment]
Following this, I have another question... I'm implementing a sidebar from TailwindUI... that's basically a dropdown too, but with two targets that need transforms (menu and backdrop).

So I thought of subclassing Dropdown and adding another target... would you be interested in that controller as well?

**Comment by excid3** [comment]
Hmm, the background did not always do that. Must have been one of the recent changes broke it.

And I guess it depends on how much of a breaking change it is? If it's not too bad to upgrade, we can make it a breaking version release and notes to upgrade. Otherwise it may make more sense as a separate controller?

**Comment by julianrubisch** [comment]
Yeah definitely a separate controller. Once we get this sorted I can whip up a second PR quickly

**Comment by julianrubisch** [comment]
I think the activeTarget was added in https://github.com/excid3/tailwindcss-stimulus-components/issues/37

It looks like a valid change though, to visually indicate that the dropdown is opened?

I think this PR is safe to merge...

**Comment by excid3** [comment]
Oh yeah, forgot about the active target since I've never used it lol. 

Could you update the `docs/index.html` with the attributes for animations? I think we can get rid of the active-target in the example since we're not really using it.

**Comment by julianrubisch** [comment]
I think there's still some kind of misunderstanding on my part. I thought `_activeClassList` was the one responsible for bringing in the transition properties. 

I'm gonna rewrite this again to `_visibleClassList` and `_invisibleClassList`.

**Comment by julianrubisch** [comment]
Updated. Note: The deploy preview is using the packaged version of tailwindcss-stimulus-components, correct? So to test it you'll need to actually check it out...

**Comment by excid3** [comment]
I think `activeClassList` was added so you can add classes to the open/close element when the dropdown is open. 

The animations would be applied to the menu, not the open/close element, right?

And I agree on the confusion, haha! It might be time to rename some targets to be more clear.

**Comment by excid3** [comment]
And yes, the github page is using the npm package and I'll clone the branch to test it out locally.

**Comment by julianrubisch** [comment]
Should now work as expected!

**Comment by excid3** [comment]
Thanks @julianrubisch! Just published as v2.0.10 🙏

**Pull request merged**
