### PR TITLE
[WIP] - Add tests proposal

### PR DESCRIPTION
**Pull request by williamkennedy**
Hey @excid3 

How are you?

Hope you don't mind but I was looking at making it easier to add changes in the future as I noticed recent pull requests probably needed a lot of manual testing. My hope is that this will eventually make it easier for others to join in, test and contribute.

Before merging this in, I would like to add some more tests but just thought I would give you a heads up before I continue and see your thoughts. 

To run tests, you should be able to just call

```
yarn test
```

Thanks,
William

### CODE REVIEW

**Comment by excid3** [comment]
Love this, thanks @williamkennedy! 👍 

I have wanted to do this forever but just haven't had the time. We should absolutely set up GitHub Actions to run the tests as well so we can have them automatically run on PRs.

**Comment by williamkennedy** [comment]
Thanks Chris. Just so you know, I have another branch where I'm experimenting with Karma js. 

Currently, I'm in two minds about the limitations of either. This PR is using Jest which uses jsdom. I don't know how much of a limitation it could be when we introduce more and more complicated changes such as CSS animations. 

Yes Github actions is a good idea. We could also have a watcher that reacts to code changes when your working on the project. 

I'll have my results soon and let you know. Thanks for the feedback.

**Comment by excid3** [comment]
I haven't used Karma, so I'm curious to check that out. I've used Jest before and it works well.

Dropdowns and Slideovers should have some animations, so if we can test those with Jest and it works, then perfect. I don't know that we need very thorough tests around the animations, just that the classes are added and removed correctly. I would imagine that would be about the same as regular tests we'd have for tabs, etc.

**Comment by williamkennedy** [comment]
Perfect.

Leave it with me. If we can test that transitions are being applied, then I think we're good

**Comment by excid3** [comment]
I merged this on the command line and now can't merge this because of conflicts. Derp. Closing but it's merged!

**Comment by williamkennedy** [comment]
woohoo

**Pull request closed without merging**
