### PR TITLE
tabs: better event and active attribute

### PR DESCRIPTION
**Pull request by dbil25**
this PR
- Adds an `active="true"` attribute to the active tab. Useful when you want some other javascript to we aware of which tab is active
- Rename the dispatched event (might be breaking if some users relied on it) to be stimulus-y but using the [stimulus dispatch function](https://stimulus.hotwired.dev/reference/controllers#cross-controller-coordination-with-events) that will send the event `tabs:tab-changed` with `event.target` beeing the tab element itself and `event.detail` beeing `{ activeIndex: n}`

### CODE REVIEW

**Comment by excid3** [comment]
Does the existing `data-index-value` for the current tab do the job of `active="true"` it may not be as convenient, but it's already there for that purpose.

Switching to `this.dispatch()` is a good idea. 👍

**Comment by dbil25** [comment]
Having the active attribute allows me to do some tailwind shenanigans like 'group-[&:active]:some-cool-class' it could also be a data-attribute like data-active if you think its more appropriate

**Comment by excid3** [comment]
Probably best to stick with `data-active="true"` but that seems like good enough reasoning to me.

**Comment by dbil25** [comment]
there you go

**Comment by excid3** [comment]
Thanks @dbil25 👍

**Pull request merged**
